repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2  # You might want to use a newer version if available
    hooks:
    -   id: flake8
