name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Build and tag Docker image
      run: |
        docker build . -t modpack.azurecr.io/modpack-inspector:${{ github.sha }}
        echo ${{ secrets.AZURE_REGISTRY_PASSWORD }} | docker login modpack.azurecr.io -u ${{ secrets.AZURE_REGISTRY_USERNAME }} --password-stdin

    - name: Push Docker image to Azure Container Registry
      run: |
        docker push modpack.azurecr.io/modpack-inspector:${{ github.sha }}

    - name: Deploy to Azure Container Instances
      uses: azure/aci-deploy@v1
      with:
        resource-group: modpack-inspector-group
        image: modpack.azurecr.io/modpack-inspector:${{ github.sha }}
        registry-login-server: modpack.azurecr.io
        registry-username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        registry-password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
        name: modpack-inspector-aci
        location: eastus
